input-output-hk/cardano-clusterlib-py

- cardano_clusterlib/clusterlib.py
CLI args changed in https://github.com/input-output-hk/cardano-node/pull/2547
> Fix scripts-related CLI args

- cardano_clusterlib/clusterlib.py
* `utxo_ix` is integer
* txouts can be empty
* possibility to check if output file already exists
> Misc fixes and enhancements

- cardano_clusterlib/clusterlib.py
Refactor `get_txid_body` and `get_txid_signed` to single `get_txid`.
> Add stake-snapshot, pool-params, transaction view

- cardano_clusterlib/clusterlib.py
See https://github.com/input-output-hk/cardano-node/pull/3146
> Make `get_utxo` work with base16 encoded asset names

- cardano_clusterlib/clusterlib.py
and remove dprecated `calculate-min-value`.
> Add support for `calculate-min-required-utxo`

- cardano_clusterlib/clusterlib.py
See https://github.com/input-output-hk/cardano-node/pull/3211
> AssetName as hex string

- cardano_clusterlib/clusterlib.py
* explicit splits by whitespace
* comment
* default value for optional string
> Minor tweaks

- cardano_clusterlib/clusterlib.py
Return relevant part of tip info from functions that wait for certain slot, block or epoch number.
> Return tip

- cardano_clusterlib/clusterlib.py
that wraps `query leadership-schedule` CLI command.
> Add `get_leadership_schedule`

- cardano_clusterlib/clusterlib.py
For some `cardano-cli` commands the order of arguments matter. This is the case of scripts-related commands.
Adding the missing functionality required also changes to minting scripts and Tx input scripts.
> Add support for Plutus scripts for cetificates and withdrawal

- cardano_clusterlib/clusterlib.py
Raise `CLIError` on runtime errors, raise `AssertionError` on wrong arguments passed to method.
> Unify raised exceptions

- cardano_clusterlib/clusterlib.py
and use it where needed (namely 'decentralization: 0 vs null')
> Generate backwards compatible protocol params file

- cardano_clusterlib/clusterlib_klass.py
`cardano-cli query utxo` supports querying multiple addresses or txins.
Fixes https://github.com/input-output-hk/cardano-clusterlib-py/issues/111
> Add possibility to pass multiple addresses or txins to `get_utxo`

- cardano_clusterlib/clusterlib_klass.py
Wait for new block even in case of failed re-submit, because UTxO can be queried even when transactions is in mempool.
> Fix transaction re-submit

- cardano_clusterlib/stake_address_group.py
> add stake-address option to stake-address certificate commands

- cardano_clusterlib/transaction_group.py
while waiting for the transaction to be removed from mempool.
> Try to resubmit a transaction up to 20 times

- cardano_clusterlib/structs.py
- cardano_clusterlib/transaction_group.py
- cardano_clusterlib/txtools.py
There are many different sources of reference Tx inputs, lets create a combined list.
> Combine all reference Tx inputs in `TxRawOutput` data structure

- cardano_clusterlib/txtools.py
- Capitalize comments for consistency.
- Filter out negative amounts earlier in the function.
- Add early return if `skip_asset_balancing` is True.
- Remove redundant filtering of negative amounts at the end.
> fix(txouts): improve txouts balancing logic

- cardano_clusterlib/clusterlib_helpers.py
- cardano_clusterlib/clusterlib_klass.py
Added a `wait_for_epoch` function for waiting for a specific epoch.
Moved the logic for waiting for epochs from the ClusterLib class to helper functions in clusterlib_helpers.py. This refactor improves code modularity and reusability.
> feat(waiting): add `wait_for_epoch` function

- cardano_clusterlib/clusterlib.py
- cardano_clusterlib/clusterlib_helpers.py
- cardano_clusterlib/clusterlib_klass.py
- cardano_clusterlib/consts.py
- cardano_clusterlib/query_group.py
- cardano_clusterlib/transaction_group.py
The only usable protocol mode in Conway is full Cardano mode.
> refactor: remove protocol handling from ClusterLib

- cardano_clusterlib/transaction_group.py
Extended the transaction group to handle DRep deposits and retirements, and stake address registration combined with drep delegation.
> feat(transaction): add support for more certs for deposit

- cardano_clusterlib/transaction_group.py
- Updated `submit_tx_bare` to return transaction ID (txid) as a string.
- Modified `submit_tx` to return transaction ID (txid) as a string.
- Added extraction of txid from the CLI output in `submit_tx_bare`.
- Ensured `submit_tx` captures and returns the txid from `submit_tx_bare`.
> feat(transaction): return txid from submit_tx and submit_tx_bare

- cardano_clusterlib/clusterlib_helpers.py
- cardano_clusterlib/clusterlib_klass.py
- cardano_clusterlib/query_group.py
- cardano_clusterlib/stake_address_group.py
- cardano_clusterlib/stake_pool_group.py
- cardano_clusterlib/structs.py
- cardano_clusterlib/transaction_group.py
- cardano_clusterlib/txtools.py
- cardano_clusterlib/types.py
Capitalized the first letter of comments across various files in the cardano_clusterlib module to maintain consistency and improve readability.
> chore: Capitalize comments in multiple files

- cardano_clusterlib/clusterlib_klass.py
- cardano_clusterlib/txtools.py
- docs/source/conf.py
- pyproject.toml
Refactored code to use the max function for better readability and consistency. Updated the pyproject.toml to include new linting rules.
> refactor: use max function for clarity
