cardano_clusterlib/clusterlib.py
On Mary `--ttl` and `--invalid-hereafter` are optional.
=> Make ttl optional on Mary

cardano_clusterlib/clusterlib.py
It's also optional now, in preparation for CLI automation.
=> Execution units are now rationals instead of integers

cardano_clusterlib/clusterlib.py
The default value should work for both mainnet and testnet. However
proper calculation based on transaction size and `utxoCostPerWord` is
needed.
See https://github.com/input-output-hk/cardano-clusterlib-py/issues/52
=> Add default value for `_min_change_value`

cardano_clusterlib/clusterlib.py
The cli currently has an intermediate TxBody type that is serialised in an intermediate format which does not follow cardano-ledger's CDDL spec.
A flag was added to the cli allowing the CDDL serialisation of any relevant outputs. Eventually the cli's intermediate format will be deprecated.
See https://github.com/input-output-hk/cardano-node/issues/3544
=> Add support for `--cddl-format` option

cardano_clusterlib/clusterlib.py
The UTxO datum hash key was called "data", now it is "datumhash".
=> Fix reading of UTxO record datum hash

cardano_clusterlib/clusterlib_helpers.py, cardano_clusterlib/clusterlib_klass.py
Quote arguments with spaces and other "special" characters in them in the same way these would be formatted when entered into command line manually. E.g.
```
cardano-cli transaction build --tx-in "03eee85081ad76948094d3acbaae44fdf725f4998a89b33a0f8ecea65b2af921#1" --tx-out "addr_test1vzhx4xqz6t3qdf3pklgx5m724quqemszjehqm2s5mau5f5gpk0q29+2000000" --change-address addr_test1vp50wj6q0ut0vdqcw0dn79eh8gh0dt5ytq6vm5v0a3h53rq6m4pl2 --out-file tx.body
```
=> Format CLI arguments for logging

cardano_clusterlib/conway_gov_query_group.py
The structure for querying committee state has changed and now response looks like this:
```
reg_committee_state = cluster.g_conway_governance.query.committee_state()
In [1]: reg_committee_state
Out[1]: 
{'committee': {'keyHash-8176f4b039be7e2b3a31ab4a9a5e802170256e28966ee65de60d1075': {'expiration': None,
'hotCredsAuthStatus': {'contents': {'keyHash': '14c93febe6db1c1e9d7855197e9c5bbebf0b10016ee3f07c1bff0026'},
'tag': 'MemberAuthorized'},
'nextEpochChange': 'NoChangeExpected',
'status': 'Unrecognized'}},
'epoch': 23,
'quorum': 0.0}
```
=> Update committee query return type

cardano_clusterlib/conway_gov_drep_group.py, cardano_clusterlib/conway_gov_query_group.py
This pull request adds a missing option `--drep-script-hash` to include a drep script hash in case of generating drep retirement certificate using gen_retirement_cert on drep group cli commands.
=> Add --drep-script-hash option for drep retirement and drep state query

cardano_clusterlib/conway_gov_query_group.py
We now support also scripts, not only key credentials.
=> Rename `key_args` to more fitting `cred_args`

cardano_clusterlib/conway_gov_group.py
The `hash` command was moved from `conway governance` group to top level.
=> Fix calls to `cardano-cli hash`

cardano_clusterlib/clusterlib.py, cardano_clusterlib/conway_gov_action_group.py, cardano_clusterlib/structs.py, cardano_clusterlib/transaction_group.py, cardano_clusterlib/txtools.py
This PR adds support for creating an action file with constitution_script_hash in create_constitution function inside the Conway gov action group. And adds support for the proposal, which requires a constitutional script for the transaction.
Optional `ComplexProposal`, similar to other data structures such as `ComplexCert`, is used to obtain the required script and redeemer value for the proposal file when building the transaction with build_tx or build_raw_tx.
=> Adds support for proposals with script in transaction group and constitution_script_hash in action group

cardano_clusterlib/structs.py, cardano_clusterlib/transaction_group.py, cardano_clusterlib/txtools.py
Add support for treasury donations.
- adds `--treasury-donation` to `transaction build`
- adds `--current-treasury-value` and `--treasury-donation` to `transaction build-raw`
In case of `transaction build-raw` donation must be passed together with current treasury value.
=> Add treasury donation for build tx command

cardano_clusterlib/structs.py
The `CCMember` can represent both key and script.
=> Remove hot keys record from `CCMember`

cardano_clusterlib/transaction_group.py, cardano_clusterlib/txtools.py
When using `transaction build`, don't perform balancing of assets (both Lovelace and multi-assets) in the library and leave the balancing to the the CLI.
The `lovelace_balanced` flag has been removed from various functions including `_balance_txouts`, `_get_tx_ins_outs`, and `collect_data_for_build`. This change simplifies the code by relying on the `skip_asset_balancing` for both Lovelace and multi-assets.
=> feat(balancing): make `build` autobalance assets

.pre-commit-config.yaml
Updated the ruff-pre-commit hook from version v0.5.5 to v0.6.3 in the .pre-commit-config.yaml file. This ensures we are using the latest features and fixes provided by the ruff-pre-commit tool.
=> chore: update ruff-pre-commit to v0.6.3

cardano_clusterlib/genesis_group.py, cardano_clusterlib/governance_group.py
Use the 'legacy' CLI group for commands that no longer work in Conway era.
=> feat: use the 'legacy' group for 'genesis' and 'governance'

README.md, cardano_clusterlib/clusterlib_klass.py, cardano_clusterlib/consts.py, cardano_clusterlib/transaction_group.py
The tx_era parameter has been removed from the ClusterLib class and related methods. Updated documentation and internal logic to reflect these changes.
=> refactor: remove deprecated tx_era parameter

cardano_clusterlib/address_group.py, cardano_clusterlib/transaction_group.py
This commit removes the deprecated methods `gen_script_addr` from `address_group.py` and `calculate_min_value` from `transaction_group.py`. Additionally, it removes the associated warnings related to these methods.
=> refactor: remove deprecated methods and warnings

cardano_clusterlib/clusterlib.py, cardano_clusterlib/clusterlib_klass.py, cardano_clusterlib/consts.py, cardano_clusterlib/stake_address_group.py, cardano_clusterlib/transaction_group.py, cardano_clusterlib/txtools.py
- Replace string literals with constants from CommandEras class.
- Add error handling for unknown command eras.
- Update method signatures and internal logic to use era_in_use.
- Remove redundant command_era checks and arguments.
- Simplify proposal file argument name determination.
=> refactor: update command era handling in ClusterLib

README.md, cardano_clusterlib/clusterlib.py, cardano_clusterlib/clusterlib_helpers.py, cardano_clusterlib/clusterlib_klass.py, cardano_clusterlib/consts.py
Removed the hardcoded slots_offset and replaced it with a dynamic calculation based on the current testnet configuration. This change improves flexibility and accuracy when dealing with different testnets in the Cardano blockchain.
=> refactor: remove slots_offset and add dynamic calculation

.gitignore
- Add /tmp*, /.bin*, and /.patches/ to ignore local files
- Add .dmypy.json to ignore mypy cache
- Add /tags to ignore Exuberant Ctags tag file
- Add /.source* to ignore environment variable files
=> chore: update .gitignore for local and env files

.pre-commit-config.yaml, cardano_clusterlib/__init__.py, pyproject.toml
- Bump pre-commit hooks versions in .pre-commit-config.yaml
- Reformat code with the new ruff
- Update ignore rules in pyproject.toml for ruff
=> chore: update pre-commit hooks and fix imports

docs/requirements.txt
Updated Sphinx to version 8.1.3, m2r2 to version 0.3.3.post2, sphinx-rtd-theme to version 3.0.1, and added docutils version 0.20.1 to make builds more predictable.
Also fixes
```
Exception occurred:
File "/home/docs/checkouts/readthedocs.org/user_builds/cardano-clusterlib-py/envs/latest/lib/python3.10/site-packages/m2r2.py", line 611, in run
path = nodes.reprunicode(path)
AttributeError: module 'docutils.nodes' has no attribute 'reprunicode'
```
=> fix(docs): pin documentation dependencies

cardano_clusterlib/clusterlib_klass.py, cardano_clusterlib/consts.py, cardano_clusterlib/transaction_group.py
- Added `confirm_blocks` property to `ClusterLib` class.
- Set default value for `CONFIRM_BLOCKS_NUM` in `consts.py`.
- Updated `submit_tx` method in `TransactionGroup` to use `confirm_blocks`.
=> feat: add confirm_blocks property to ClusterLib

Makefile, requirements-dev.txt
Removed redundant build installation from Makefile and added it to requirements-dev.txt to ensure all dependencies are managed in one place.
=> chore: add build dependency to requirements-dev.txt

cardano_clusterlib/transaction_group.py, cardano_clusterlib/txtools.py
This change optimizes UTxO retrieval by avoiding redundant queries.
=> feat: avoid redundant UTxO queries

cardano_clusterlib/clusterlib.py, cardano_clusterlib/clusterlib_klass.py, cardano_clusterlib/conway_gov_action_group.py, cardano_clusterlib/conway_gov_vote_group.py, cardano_clusterlib/query_group.py, cardano_clusterlib/stake_address_group.py, cardano_clusterlib/structs.py, cardano_clusterlib/transaction_group.py, cardano_clusterlib/txtools.py, cardano_clusterlib/types.py
Removed unnecessary pylint disable comments from various files in the cardano_clusterlib module. We no longer use pylint.
=> refactor: remove pylint disable comments

.pre-commit-config.yaml
Updated the ruff-pre-commit hook version from v0.8.3 to v0.9.2 in the .pre-commit-config.yaml file to ensure compatibility with the latest features and fixes.
=> chore: update ruff-pre-commit to v0.9.2

Makefile
Updated the Makefile to call pytype with '-k -j auto' options (continue on error and run checks in parallel).
=> fix(makefile): update pytype command

cardano_clusterlib/query_group.py, cardano_clusterlib/structs.py
Renamed the key `delegation_deposit` to `registration_deposit` in `cardano_clusterlib/query_group.py` and `cardano_clusterlib/structs.py` to reflect the correct terminology.
=> feat: get registration deposit using he renamed key

cardano_clusterlib/address_group.py, cardano_clusterlib/clusterlib_klass.py, cardano_clusterlib/conway_gov_drep_group.py, cardano_clusterlib/genesis_group.py, cardano_clusterlib/governance_group.py, cardano_clusterlib/node_group.py, cardano_clusterlib/query_group.py, cardano_clusterlib/stake_address_group.py, cardano_clusterlib/stake_pool_group.py, cardano_clusterlib/transaction_group.py, cardano_clusterlib/txtools.py
Updated docstrings across multiple files to replace 'tuple' with 'data container' for better clarity. The data containers were using `NamedTuple` in the past, now we use frozen dataclasses.
=> refactor: update docstrings to use 'data container'

cardano_clusterlib/query_group.py
- Added `get_drep_deposit` method to retrieve DRep deposit amount.
- Added `get_gov_action_deposit` method to retrieve governance action deposit amount.
=> feat(query_group): add methods for DRep and gov action deposits

cardano_clusterlib/query_group.py, cardano_clusterlib/transaction_group.py
- Updated `get_address_deposit`, `get_pool_deposit`, `get_drep_deposit`, and `get_gov_action_deposit` methods in `query_group.py` to accept an optional `pparams` argument.
- Modified `transaction_group.py` to use the updated methods with `pparams` argument.
=> feat: add optional pparams argument to deposit methods

cardano_clusterlib/query_group.py
Added an optional `tip` parameter to several methods in the `QueryGroup` class. This allows passing a pre-fetched tip dictionary to avoid redundant calls to `get_tip()`, improving efficiency.
=> feat(query_group): add optional tip parameter to methods

cardano_clusterlib/transaction_group.py
- Added retrieval of governance action deposit in TransactionGroup.
- Updated deposit calculation to include governance proposal files.
=> feat(transaction): add governance action deposit handling

cardano_clusterlib/query_group.py
- Changed `utxo` command to use `--output-json` for JSON output.
- Updated `stake-distribution` and `stake-pools` commands to include `--output-text` for text output.
- Added `--output-text` to `leadership-schedule` command for consistency.
=> feat(query_group): update CLI commands for output format

cardano_clusterlib/transaction_group.py
Add the `--output-text` flag to `transaction txid` and `transaction calculate-min-fee` CLI commands to ensure output is in plain text format.
=> feat(transaction): add --output-text flag to CLI commands

cardano_clusterlib/transaction_group.py
Add the `--output-text` flag conditionally for CLI versions >= 10.7.0.0 to ensure compatibility with changes in default output format.
=> feat(transaction): add conditional `--output-text` flag

cardano_clusterlib/conway_gov_query_group.py
Update the `drep_stake_distribution` method to return a dictionary instead of a list of lists. The new `cardano-cli` returns dict instead of list of list, and this change unifies the output of the old and new `cardano-cli` versions.
=> feat(conway_gov_query_group): return dict for `drep_stake_distribution`

cardano_clusterlib/consts.py
Remove the legacy era constants (SHELLEY, ALLEGRA, MARY, ALONZO, BABBAGE) from the CommandEras class in consts.py. Only CONWAY and LATEST are now retained, reflecting current usage and simplifying the codebase.
=> refactor(consts): remove unused legacy era constants

cardano_clusterlib/transaction_group.py
The `witness_count` parameter in the `TransactionGroup._estimate_tx_size` method is now required instead of having a default value. This change removes ambiguity and enforces explicit specification of the witness count when estimating transaction size.
=> fix(transaction_group): make witness_count argument required

cardano_clusterlib/transaction_group.py
- Add `--output-json` flag to the `transaction view` CLI call to explicitly enable JSON output.
- Introduce `view_tx_dict` method to parse the transaction view output into a Python dictionary for easier programmatic access.
=> feat(tx-group): add JSON output and dict view for tx

.pre-commit-config.yaml, cardano_clusterlib/clusterlib_klass.py, cardano_clusterlib/txtools.py, pyproject.toml, requirements-dev.txt
- Add pyrefly to pre-commit hooks and development requirements.
- Configure pyrefly in pyproject.toml with project-specific settings and per-file ignores.
- Update ruff linting rules to include ANN and add per-file ignore for docs.
- Pin mypy and pre-commit versions for consistency.
- Add pyrefly ignore comments in code to suppress specific errors.
=> feat(lint): add pyrefly and update linting configs

cardano_clusterlib/helpers.py, cardano_clusterlib/query_group.py, cardano_clusterlib/stake_pool_group.py, cardano_clusterlib/transaction_group.py, cardano_clusterlib/txtools.py
Update type hints to use builtin generics (e.g., list, tuple) instead of capitalized versions (e.g., List, Tuple) in docstrings and return annotations. This improves consistency with modern Python typing conventions.
=> refactor: use builtin generics for type hints in docstrings

.github/workflows/repo_tests.yaml, .pre-commit-config.yaml, Makefile, cardano_clusterlib/clusterlib_klass.py, cardano_clusterlib/txtools.py, docs/source/conf.py, requirements-dev.txt
- Rename and update GitHub Actions workflow to `repo_tests`, using Python 3.12, venv, and improved pre-commit caching and activation.
- Update pre-commit config: bump ruff and markdownlint versions, move pyrefly hook, and update ruff hook id.
- Update Makefile to require virtualenv for pip installs and improve commands.
- Bump mypy and pyrefly versions in requirements-dev.txt.
- Minor code cleanups: remove obsolete pyrefly ignore comments, clarify variable names, and use context manager for subprocess in docs conf.py.
=> chore: update linting, CI, and dependencies

pyproject.toml
Switch to setuptools 'packages.find' for package discovery in pyproject.toml. This ensures all cardano_clusterlib* packages are included correctly.
=> fix(build): update setuptools package discovery config
